# Generated by Django 6.0.5 on 2026-05-31 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название клуба')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('stadium', models.CharField(max_length=100, verbose_name='Стадион')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.country', verbose_name='Страна')),
            ],
        ),
    ]
