# Generated by Django 6.0.5 on 2026-05-31 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalog.club', verbose_name='Клуб'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(choices=[('GK', 'Вратарь'), ('DEF', 'Защитник'), ('MID', 'Полузащитник'), ('FWD', 'Нападающий')], max_length=3, verbose_name='Позиция')),
                ('number', models.IntegerField(verbose_name='Игровой номер')),
                ('is_captain', models.BooleanField(default=False, verbose_name='Капитан')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='catalog.club', verbose_name='Клуб')),
            ],
        ),
    ]
