# Generated by Django 6.0.5 on 2026-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_coach_club_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название награды')),
                ('players', models.ManyToManyField(blank=True, related_name='awards', to='catalog.player', verbose_name='Игроки')),
            ],
        ),
    ]
